
const TEST0 := &"Feature"
const TEST1 := &"Terrain"
const TEST2 := &"Object"
const TEST3 := &"Action"
const TEST4 := &"Concept"
const TEST5 := &"Category"
const TEST6 := &"Carrot"
const TEST6a := &"Contemplate"

const TEST7 := &"Terraform"
const TEST8 := &"Feed"
const TEST9 := &"Active"
const TEST10 := &"Get"
const TEST11 := &"Douse"
const TEST12 := &"Drab"
const TEST13 := &"Drop"

const TEST14 := &"Drink"
const TEST15 := &"Dank"
const TEST16 := &"Terrasque"
const TEST17 := &"Trunk"
const TEST18 := &"Cargo"
